# Generated by Django 2.0.6 on 2018-07-02 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_user_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_users',
        ),
    ]
