# Generated by Django 2.0.6 on 2018-06-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='test',
            field=models.TextField(null=True),
        ),
    ]
