# Generated by Django 2.0.6 on 2018-06-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postcomment_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='test',
        ),
    ]
