# Generated by Django 2.0.6 on 2018-06-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_postcomment_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
